version: '3'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: log_db
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
    restart: always
    ports:
      - 3000:3000
